- id: "NuGet::Microsoft.Extensions.Configuration.KeyPerFile:"
  curations:
    comment: "Set the VCS path of the module inside the multi-module repository."
    vcs:
      path: "src/Configuration.KeyPerFile/src"
