- id: "NuGet::Microsoft.Extensions.Configuration.Abstractions:"
  curations:
    comment: "Set the VCS path of the module inside the multi-module repository."
    vcs:
      path: "src/libraries/Microsoft.Extensions.Configuration.Abstractions"
